
export interface Country {
  name: string;
  dial_code: string;
  code: string;
  emoji: string;
}

export const countriesData: Country[] = [
  { name: "France", dial_code: "+33", code: "FR", emoji: "🇫🇷" },
  { name: "Afghanistan", dial_code: "+93", code: "AF", emoji: "🇦🇫" },
  { name: "Afrique du Sud", dial_code: "+27", code: "ZA", emoji: "🇿🇦" },
  { name: "Albanie", dial_code: "+355", code: "AL", emoji: "🇦🇱" },
  { name: "Algérie", dial_code: "+213", code: "DZ", emoji: "🇩🇿" },
  { name: "Allemagne", dial_code: "+49", code: "DE", emoji: "🇩🇪" },
  { name: "Andorre", dial_code: "+376", code: "AD", emoji: "🇦🇩" },
  { name: "Angola", dial_code: "+244", code: "AO", emoji: "🇦🇴" },
  { name: "Antigua-et-Barbuda", dial_code: "+1268", code: "AG", emoji: "🇦🇬" },
  { name: "Arabie saoudite", dial_code: "+966", code: "SA", emoji: "🇸🇦" },
  { name: "Argentine", dial_code: "+54", code: "AR", emoji: "🇦🇷" },
  { name: "Arménie", dial_code: "+374", code: "AM", emoji: "🇦🇲" },
  { name: "Australie", dial_code: "+61", code: "AU", emoji: "🇦🇺" },
  { name: "Autriche", dial_code: "+43", code: "AT", emoji: "🇦🇹" },
  { name: "Azerbaïdjan", dial_code: "+994", code: "AZ", emoji: "🇦🇿" },
  { name: "Bahamas", dial_code: "+1242", code: "BS", emoji: "🇧🇸" },
  { name: "Bahreïn", dial_code: "+973", code: "BH", emoji: "🇧🇭" },
  { name: "Bangladesh", dial_code: "+880", code: "BD", emoji: "🇧🇩" },
  { name: "Barbade", dial_code: "+1246", code: "BB", emoji: "🇧🇧" },
  { name: "Belgique", dial_code: "+32", code: "BE", emoji: "🇧🇪" },
  { name: "Belize", dial_code: "+501", code: "BZ", emoji: "🇧🇿" },
  { name: "Bénin", dial_code: "+229", code: "BJ", emoji: "🇧🇯" },
  { name: "Bhoutan", dial_code: "+975", code: "BT", emoji: "🇧🇹" },
  { name: "Biélorussie", dial_code: "+375", code: "BY", emoji: "🇧🇾" },
  { name: "Birmanie", dial_code: "+95", code: "MM", emoji: "🇲🇲" },
  { name: "Bolivie", dial_code: "+591", code: "BO", emoji: "🇧🇴" },
  { name: "Bosnie-Herzégovine", dial_code: "+387", code: "BA", emoji: "🇧🇦" },
  { name: "Botswana", dial_code: "+267", code: "BW", emoji: "🇧🇼" },
  { name: "Brésil", dial_code: "+55", code: "BR", emoji: "🇧🇷" },
  { name: "Brunei", dial_code: "+673", code: "BN", emoji: "🇧🇳" },
  { name: "Bulgarie", dial_code: "+359", code: "BG", emoji: "🇧🇬" },
  { name: "Burkina Faso", dial_code: "+226", code: "BF", emoji: "🇧🇫" },
  { name: "Burundi", dial_code: "+257", code: "BI", emoji: "🇧🇮" },
  { name: "Cambodge", dial_code: "+855", code: "KH", emoji: "🇰🇭" },
  { name: "Cameroun", dial_code: "+237", code: "CM", emoji: "🇨🇲" },
  { name: "Canada", dial_code: "+1", code: "CA", emoji: "🇨🇦" },
  { name: "Cap-Vert", dial_code: "+238", code: "CV", emoji: "🇨🇻" },
  { name: "Chili", dial_code: "+56", code: "CL", emoji: "🇨🇱" },
  { name: "Chine", dial_code: "+86", code: "CN", emoji: "🇨🇳" },
  { name: "Chypre", dial_code: "+357", code: "CY", emoji: "🇨🇾" },
  { name: "Colombie", dial_code: "+57", code: "CO", emoji: "🇨🇴" },
  { name: "Comores", dial_code: "+269", code: "KM", emoji: "🇰🇲" },
  { name: "Congo", dial_code: "+242", code: "CG", emoji: "🇨🇬" },
  { name: "Corée du Nord", dial_code: "+850", code: "KP", emoji: "🇰🇵" },
  { name: "Corée du Sud", dial_code: "+82", code: "KR", emoji: "🇰🇷" },
  { name: "Costa Rica", dial_code: "+506", code: "CR", emoji: "🇨🇷" },
  { name: "Côte d'Ivoire", dial_code: "+225", code: "CI", emoji: "🇨🇮" },
  { name: "Croatie", dial_code: "+385", code: "HR", emoji: "🇭🇷" },
  { name: "Cuba", dial_code: "+53", code: "CU", emoji: "🇨🇺" },
  { name: "Danemark", dial_code: "+45", code: "DK", emoji: "🇩🇰" },
  { name: "Djibouti", dial_code: "+253", code: "DJ", emoji: "🇩🇯" },
  { name: "Dominique", dial_code: "+1767", code: "DM", emoji: "🇩🇲" },
  { name: "Égypte", dial_code: "+20", code: "EG", emoji: "🇪🇬" },
  { name: "Émirats arabes unis", dial_code: "+971", code: "AE", emoji: "🇦🇪" },
  { name: "Équateur", dial_code: "+593", code: "EC", emoji: "🇪🇨" },
  { name: "Érythrée", dial_code: "+291", code: "ER", emoji: "🇪🇷" },
  { name: "Espagne", dial_code: "+34", code: "ES", emoji: "🇪🇸" },
  { name: "Estonie", dial_code: "+372", code: "EE", emoji: "🇪🇪" },
  { name: "États-Unis", dial_code: "+1", code: "US", emoji: "🇺🇸" },
  { name: "Éthiopie", dial_code: "+251", code: "ET", emoji: "🇪🇹" },
  { name: "Fidji", dial_code: "+679", code: "FJ", emoji: "🇫🇯" },
  { name: "Finlande", dial_code: "+358", code: "FI", emoji: "🇫🇮" },
  { name: "Gabon", dial_code: "+241", code: "GA", emoji: "🇬🇦" },
  { name: "Gambie", dial_code: "+220", code: "GM", emoji: "🇬🇲" },
  { name: "Géorgie", dial_code: "+995", code: "GE", emoji: "🇬🇪" },
  { name: "Ghana", dial_code: "+233", code: "GH", emoji: "🇬🇭" },
  { name: "Grèce", dial_code: "+30", code: "GR", emoji: "🇬🇷" },
  { name: "Grenade", dial_code: "+1473", code: "GD", emoji: "🇬🇩" },
  { name: "Guatemala", dial_code: "+502", code: "GT", emoji: "🇬🇹" },
  { name: "Guinée", dial_code: "+224", code: "GN", emoji: "🇬🇳" },
  { name: "Guinée équatoriale", dial_code: "+240", code: "GQ", emoji: "🇬🇶" },
  { name: "Guinée-Bissau", dial_code: "+245", code: "GW", emoji: "🇬🇼" },
  { name: "Guyana", dial_code: "+592", code: "GY", emoji: "🇬🇾" },
  { name: "Haïti", dial_code: "+509", code: "HT", emoji: "🇭🇹" },
  { name: "Honduras", dial_code: "+504", code: "HN", emoji: "🇭🇳" },
  { name: "Hongrie", dial_code: "+36", code: "HU", emoji: "🇭🇺" },
  { name: "Îles Cook", dial_code: "+682", code: "CK", emoji: "🇨🇰" },
  { name: "Îles Marshall", dial_code: "+692", code: "MH", emoji: "🇲🇭" },
  { name: "Inde", dial_code: "+91", code: "IN", emoji: "🇮🇳" },
  { name: "Indonésie", dial_code: "+62", code: "ID", emoji: "🇮🇩" },
  { name: "Irak", dial_code: "+964", code: "IQ", emoji: "🇮🇶" },
  { name: "Iran", dial_code: "+98", code: "IR", emoji: "🇮🇷" },
  { name: "Irlande", dial_code: "+353", code: "IE", emoji: "🇮🇪" },
  { name: "Islande", dial_code: "+354", code: "IS", emoji: "🇮🇸" },
  { name: "Israël", dial_code: "+972", code: "IL", emoji: "🇮🇱" },
  { name: "Italie", dial_code: "+39", code: "IT", emoji: "🇮🇹" },
  { name: "Jamaïque", dial_code: "+1876", code: "JM", emoji: "🇯🇲" },
  { name: "Japon", dial_code: "+81", code: "JP", emoji: "🇯🇵" },
  { name: "Jordanie", dial_code: "+962", code: "JO", emoji: "🇯🇴" },
  { name: "Kazakhstan", dial_code: "+7", code: "KZ", emoji: "🇰🇿" },
  { name: "Kenya", dial_code: "+254", code: "KE", emoji: "🇰🇪" },
  { name: "Kirghizistan", dial_code: "+996", code: "KG", emoji: "🇰🇬" },
  { name: "Kiribati", dial_code: "+686", code: "KI", emoji: "🇰🇮" },
  { name: "Koweït", dial_code: "+965", code: "KW", emoji: "🇰🇼" },
  { name: "Laos", dial_code: "+856", code: "LA", emoji: "🇱🇦" },
  { name: "Lesotho", dial_code: "+266", code: "LS", emoji: "🇱🇸" },
  { name: "Lettonie", dial_code: "+371", code: "LV", emoji: "🇱🇻" },
  { name: "Liban", dial_code: "+961", code: "LB", emoji: "🇱🇧" },
  { name: "Libéria", dial_code: "+231", code: "LR", emoji: "🇱🇷" },
  { name: "Libye", dial_code: "+218", code: "LY", emoji: "🇱🇾" },
  { name: "Liechtenstein", dial_code: "+423", code: "LI", emoji: "🇱🇮" },
  { name: "Lituanie", dial_code: "+370", code: "LT", emoji: "🇱🇹" },
  { name: "Luxembourg", dial_code: "+352", code: "LU", emoji: "🇱🇺" },
  { name: "Macédoine du Nord", dial_code: "+389", code: "MK", emoji: "🇲🇰" },
  { name: "Madagascar", dial_code: "+261", code: "MG", emoji: "🇲🇬" },
  { name: "Malaisie", dial_code: "+60", code: "MY", emoji: "🇲🇾" },
  { name: "Malawi", dial_code: "+265", code: "MW", emoji: "🇲🇼" },
  { name: "Maldives", dial_code: "+960", code: "MV", emoji: "🇲🇻" },
  { name: "Mali", dial_code: "+223", code: "ML", emoji: "🇲🇱" },
  { name: "Malte", dial_code: "+356", code: "MT", emoji: "🇲🇹" },
  { name: "Maroc", dial_code: "+212", code: "MA", emoji: "🇲🇦" },
  { name: "Maurice", dial_code: "+230", code: "MU", emoji: "🇲🇺" },
  { name: "Mauritanie", dial_code: "+222", code: "MR", emoji: "🇲🇷" },
  { name: "Mexique", dial_code: "+52", code: "MX", emoji: "🇲🇽" },
  { name: "Micronésie", dial_code: "+691", code: "FM", emoji: "🇫🇲" },
  { name: "Moldavie", dial_code: "+373", code: "MD", emoji: "🇲🇩" },
  { name: "Monaco", dial_code: "+377", code: "MC", emoji: "🇲🇨" },
  { name: "Mongolie", dial_code: "+976", code: "MN", emoji: "🇲🇳" },
  { name: "Monténégro", dial_code: "+382", code: "ME", emoji: "🇲🇪" },
  { name: "Mozambique", dial_code: "+258", code: "MZ", emoji: "🇲🇿" },
  { name: "Namibie", dial_code: "+264", code: "NA", emoji: "🇳🇦" },
  { name: "Nauru", dial_code: "+674", code: "NR", emoji: "🇳🇷" },
  { name: "Népal", dial_code: "+977", code: "NP", emoji: "🇳🇵" },
  { name: "Nicaragua", dial_code: "+505", code: "NI", emoji: "🇳🇮" },
  { name: "Niger", dial_code: "+227", code: "NE", emoji: "🇳🇪" },
  { name: "Nigeria", dial_code: "+234", code: "NG", emoji: "🇳🇬" },
  { name: "Niue", dial_code: "+683", code: "NU", emoji: "🇳🇺" },
  { name: "Norvège", dial_code: "+47", code: "NO", emoji: "🇳🇴" },
  { name: "Nouvelle-Zélande", dial_code: "+64", code: "NZ", emoji: "🇳🇿" },
  { name: "Oman", dial_code: "+968", code: "OM", emoji: "🇴🇲" },
  { name: "Ouganda", dial_code: "+256", code: "UG", emoji: "🇺🇬" },
  { name: "Ouzbékistan", dial_code: "+998", code: "UZ", emoji: "🇺🇿" },
  { name: "Pakistan", dial_code: "+92", code: "PK", emoji: "🇵🇰" },
  { name: "Palaos", dial_code: "+680", code: "PW", emoji: "🇵🇼" },
  { name: "Palestine", dial_code: "+970", code: "PS", emoji: "🇵🇸" },
  { name: "Panama", dial_code: "+507", code: "PA", emoji: "🇵🇦" },
  { name: "Papouasie-Nouvelle-Guinée", dial_code: "+675", code: "PG", emoji: "🇵🇬" },
  { name: "Paraguay", dial_code: "+595", code: "PY", emoji: "🇵🇾" },
  { name: "Pays-Bas", dial_code: "+31", code: "NL", emoji: "🇳🇱" },
  { name: "Pérou", dial_code: "+51", code: "PE", emoji: "🇵🇪" },
  { name: "Philippines", dial_code: "+63", code: "PH", emoji: "🇵🇭" },
  { name: "Pologne", dial_code: "+48", code: "PL", emoji: "🇵🇱" },
  { name: "Portugal", dial_code: "+351", code: "PT", emoji: "🇵🇹" },
  { name: "Qatar", dial_code: "+974", code: "QA", emoji: "🇶🇦" },
  { name: "République centrafricaine", dial_code: "+236", code: "CF", emoji: "🇨🇫" },
  { name: "République démocratique du Congo", dial_code: "+243", code: "CD", emoji: "🇨🇩" },
  { name: "République dominicaine", dial_code: "+1809", code: "DO", emoji: "🇩🇴" },
  { name: "République tchèque", dial_code: "+420", code: "CZ", emoji: "🇨🇿" },
  { name: "Roumanie", dial_code: "+40", code: "RO", emoji: "🇷🇴" },
  { name: "Royaume-Uni", dial_code: "+44", code: "GB", emoji: "🇬🇧" },
  { name: "Russie", dial_code: "+7", code: "RU", emoji: "🇷🇺" },
  { name: "Rwanda", dial_code: "+250", code: "RW", emoji: "🇷🇼" },
  { name: "Saint-Kitts-et-Nevis", dial_code: "+1869", code: "KN", emoji: "🇰🇳" },
  { name: "Saint-Marin", dial_code: "+378", code: "SM", emoji: "🇸🇲" },
  { name: "Saint-Vincent-et-les-Grenadines", dial_code: "+1784", code: "VC", emoji: "🇻🇨" },
  { name: "Sainte-Lucie", dial_code: "+1758", code: "LC", emoji: "🇱🇨" },
  { name: "Salomon", dial_code: "+677", code: "SB", emoji: "🇸🇧" },
  { name: "Salvador", dial_code: "+503", code: "SV", emoji: "🇸🇻" },
  { name: "Samoa", dial_code: "+685", code: "WS", emoji: "🇼🇸" },
  { name: "Sao Tomé-et-Principe", dial_code: "+239", code: "ST", emoji: "🇸🇹" },
  { name: "Sénégal", dial_code: "+221", code: "SN", emoji: "🇸🇳" },
  { name: "Serbie", dial_code: "+381", code: "RS", emoji: "🇷🇸" },
  { name: "Seychelles", dial_code: "+248", code: "SC", emoji: "🇸🇨" },
  { name: "Sierra Leone", dial_code: "+232", code: "SL", emoji: "🇸🇱" },
  { name: "Singapour", dial_code: "+65", code: "SG", emoji: "🇸🇬" },
  { name: "Slovaquie", dial_code: "+421", code: "SK", emoji: "🇸🇰" },
  { name: "Slovénie", dial_code: "+386", code: "SI", emoji: "🇸🇮" },
  { name: "Somalie", dial_code: "+252", code: "SO", emoji: "🇸🇴" },
  { name: "Soudan", dial_code: "+249", code: "SD", emoji: "🇸🇩" },
  { name: "Soudan du Sud", dial_code: "+211", code: "SS", emoji: "🇸🇸" },
  { name: "Sri Lanka", dial_code: "+94", code: "LK", emoji: "🇱🇰" },
  { name: "Suède", dial_code: "+46", code: "SE", emoji: "🇸🇪" },
  { name: "Suisse", dial_code: "+41", code: "CH", emoji: "🇨🇭" },
  { name: "Suriname", dial_code: "+597", code: "SR", emoji: "🇸🇷" },
  { name: "Syrie", dial_code: "+963", code: "SY", emoji: "🇸🇾" },
  { name: "Tadjikistan", dial_code: "+992", code: "TJ", emoji: "🇹🇯" },
  { name: "Tanzanie", dial_code: "+255", code: "TZ", emoji: "🇹🇿" },
  { name: "Tchad", dial_code: "+235", code: "TD", emoji: "🇹🇩" },
  { name: "Thaïlande", dial_code: "+66", code: "TH", emoji: "🇹🇭" },
  { name: "Timor oriental", dial_code: "+670", code: "TL", emoji: "🇹🇱" },
  { name: "Togo", dial_code: "+228", code: "TG", emoji: "🇹🇬" },
  { name: "Tonga", dial_code: "+676", code: "TO", emoji: "🇹🇴" },
  { name: "Trinité-et-Tobago", dial_code: "+1868", code: "TT", emoji: "🇹🇹" },
  { name: "Tunisie", dial_code: "+216", code: "TN", emoji: "🇹🇳" },
  { name: "Turkménistan", dial_code: "+993", code: "TM", emoji: "🇹🇲" },
  { name: "Turquie", dial_code: "+90", code: "TR", emoji: "🇹🇷" },
  { name: "Tuvalu", dial_code: "+688", code: "TV", emoji: "🇹🇻" },
  { name: "Ukraine", dial_code: "+380", code: "UA", emoji: "🇺🇦" },
  { name: "Uruguay", dial_code: "+598", code: "UY", emoji: "🇺🇾" },
  { name: "Vanuatu", dial_code: "+678", code: "VU", emoji: "🇻🇺" },
  { name: "Vatican", dial_code: "+39", code: "VA", emoji: "🇻🇦" },
  { name: "Venezuela", dial_code: "+58", code: "VE", emoji: "🇻🇪" },
  { name: "Viêt Nam", dial_code: "+84", code: "VN", emoji: "🇻🇳" },
  { name: "Yémen", dial_code: "+967", code: "YE", emoji: "🇾🇪" },
  { name: "Zambie", dial_code: "+260", code: "ZM", emoji: "🇿🇲" },
  { name: "Zimbabwe", dial_code: "+263", code: "ZW", emoji: "🇿🇼" }
];
